server:
  servlet:
    context-path: /hikari-datasource

spring:
  datasource:
    ds1:
      pool-name: PT_DEV_DataSource
      jdbc-url: jdbc:oracle:thin:@172.17.209.243:1521:bidbportal
      username: u_db_pt
      password: u_db_pt
      driver-class-name: oracle.jdbc.OracleDriver
      type: com.zaxxer.hikari.HikariDataSource
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true
      connection-test-query: SELECT 1 FROM DUAL
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
